// Code generated by "stringer -type=ObjectType -output object_stringer_generated.go"; DO NOT EDIT.

package typesx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ounknown-0]
	_ = x[Obuiltin-1]
	_ = x[Oconst-2]
	_ = x[Ofunc-3]
	_ = x[Omethod-4]
	_ = x[Olabel-5]
	_ = x[Onil-6]
	_ = x[OpkgName-7]
	_ = x[OtypeName-8]
	_ = x[Ofield-9]
	_ = x[Ovar-10]
}

const _ObjectType_name = "OunknownObuiltinOconstOfuncOmethodOlabelOnilOpkgNameOtypeNameOfieldOvar"

var _ObjectType_index = [...]uint8{0, 8, 16, 22, 27, 34, 40, 44, 52, 61, 67, 71}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
