// Code generated by "marker -method IsNode -output list_marker_generated.go -type ValueSpec,FuncDecl,TypeSpec"; DO NOT EDIT.

package def

func (*ValueSpec) IsNode() {}
func (*FuncDecl) IsNode()  {}
func (*TypeSpec) IsNode()  {}
