// Code generated by "dataclass -type Node -field Ident *ast.Ident|Obj types.Object|Pkg *packages.Package -output list_dataclass_generated.go"; DO NOT EDIT.

package use

import (
	"go/ast"
	"go/types"

	"golang.org/x/tools/go/packages"
)

type Node interface {
	Ident() *ast.Ident
	Obj() types.Object
	Pkg() *packages.Package
}
type node struct {
	ident *ast.Ident
	obj   types.Object
	pkg   *packages.Package
}

func (s *node) Ident() *ast.Ident      { return s.ident }
func (s *node) Obj() types.Object      { return s.obj }
func (s *node) Pkg() *packages.Package { return s.pkg }
func NewNode(
	ident *ast.Ident,
	obj types.Object,
	pkg *packages.Package,
) Node {
	return &node{
		ident: ident,
		obj:   obj,
		pkg:   pkg,
	}
}
